### ISSUE TITLE
Push notifications

### ISSUE THREAD

**Issue by kaparray** [hazizz/hazizz-mobile#57]
Hello. help me pls. Do you have pushy in the background? I just can't make it work(

**Comment by indeednt** [comment]
Hello. Yes, we do have push to notification. It should work in theory. You can turn it on in Settings > Notification settings. Make sure you press the save button.

**Comment by indeednt** [comment]
Hi @kaparray. Yes, we do have push to notification. It should work in theory. You can turn it on in Settings > Notification settings. Make sure you press the save button.

**Comment by kaparray** [comment]
You do have push to notification in background and handle data in flutter?

**Comment by kaparray** [comment]
in theory, or are you sure it works for you?

**Comment by skornel02** [comment]
Hi @kaparray,
Currently we have only tried it in controlled environment, and it has worked consistently. We do not yet have data on how consistent it is on a wide range of devices. Theoretically you are able to process the data from the firebase message, but we currently dump it into a notification as json text.

**Comment by kaparray** [comment]
1) does the onbackgroundmessage method work for you?
2) on what devices does it work?

**Comment by indeednt** [comment]
Yes it worked when I tested it on my device, but as it was said earlier, we do not have data and haven't tested enough to know if it is working perfectly on all devices.
